# edge/ansible/inventory.example.ini
[nucs]
nuc-shop-1 ansible_host=10.0.20.10 ansible_user=tal

[nucs:vars]
mtc_cloud_url=https://mtconnect.ffmfg.com
mtc_edge_secret=REPLACE_FROM_VAULT
monitoring_vlan_interface=eth0.20
monitoring_vlan_id=20
monitoring_vlan_link=eth0
